import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import AppSiderbar from "@/components/AppSiderbar";
import LandingPage from "./page";
import { WebSocketDataProvider } from "@/componentServer/WebSocketDataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <WebSocketDataProvider>
    <html lang="es" suppressHydrationWarning>
      <body>
        {/* <AppSiderbar /> */}
        <main className="w-full  text-white ">
          <LandingPage />
        </main>
      </body>
    </html>
    </WebSocketDataProvider>
  );
}
