import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WebSocketDataProvider } from "@/componentServer/WebSocketDataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <WebSocketDataProvider>
    <html lang="es" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col bg-">
        <main className="flex-1 w-full  text-white ">
          {children}
        </main>
      </body>
    </html>
    </WebSocketDataProvider>
  );
}
